name: Check list

on: [push, pull_request]

jobs:
  build:
    name: Check list
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Build
        run: nix-shell -p ghc git --run 'runhaskell sort.hs && git --no-pager diff --no-index a.txt a-sorted.txt'
